name: backend-CI

on: push
  # pull_request:
  #   paths:
  #     - 'backend/**'
  #     - '.github/workflows/backend.yml'

jobs:

  tests:
    name: Application tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '2.7'
        working-directory: backend
      - name: Setup test database
        working-directory: backend
        env:
          RAILS_ENV: test
          DB_HOST: localhost
          DB_NAME: myapp_test
          DB_PASSWORD: ""
          DB_USERNAME: myapp
        run: |
          bin/rails db:setup
      - name: Run tests
        working-directory: backend
        run: rails test